# This is a basic workflow to help you get started with Actions

name: Pull Request Merge Watcher - Slackbot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    types:
      - closed
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  if_merged:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
            channel-id: 'C06CWCGLMAT'
            payload: |
              {
              	"blocks": [
              		{
              			"type": "header",
              			"text": {
              				"type": "plain_text",
              				"text": ":tada: Pull Request Merged"
              			}
              		},
                  {
              			"type": "context",
              			"elements": [
              				{
              					"type": "plain_text",
              					"text": ${{ toJSON(github.event.pull_request.title) }}
              				}
              			]
              		},
              		{
              			"type": "section",
              			"fields": [
              				{
              					"type": "mrkdwn",
              					"text": "*Repository:*\n<${{ github.repositoryUrl }}|${{ github.repository }}>"
              				},
              				{
              					"type": "mrkdwn",
              					"text": "*Merged by:*\n<${{ github.event.pull_request.merged_by.html_url }}|${{ github.event.pull_request.merged_by.name || 'GitHub user' }}>"
              				}
              			]
              		},
              		{
              			"type": "actions",
              			"elements": [
              				{
              					"type": "button",
              					"style": "primary",
              					"text": {
              						"type": "plain_text",
              						"text": "View Pull Request"
              					},
              					"url": "${{ github.event.pull_request.html_url }}"
              				}
              			]
              		}
              	]
              }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
